<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-F8M8PD6" name="com.training.sanity.tests.RealEstateAddNewPropertyTC76" tests="4" failures="0" timestamp="21 May 2020 06:33:02 GMT" time="97.619" errors="1">
  <testcase name="VerifyAddedProperty" time="9.683" classname="com.training.sanity.tests.RealEstateAddNewPropertyTC76">
    <error type="java.lang.AssertionError" message="expected [200,000] but found [Rs.200,000]">
      <![CDATA[java.lang.AssertionError: expected [200,000] but found [Rs.200,000]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.training.sanity.tests.RealEstateAddNewPropertyTC76.VerifyAddedProperty(RealEstateAddNewPropertyTC76.java:201)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- VerifyAddedProperty -->
  <testcase name="ValidateLoginTest" time="9.011" classname="com.training.sanity.tests.RealEstateAddNewPropertyTC76"/>
  <testcase name="LogOutTest" time="10.427" classname="com.training.sanity.tests.RealEstateAddNewPropertyTC76"/>
  <testcase name="ValidateNewProperty" time="68.498" classname="com.training.sanity.tests.RealEstateAddNewPropertyTC76"/>
</testsuite> <!-- com.training.sanity.tests.RealEstateAddNewPropertyTC76 -->
